### PR TITLE
chore: add missing types

### PR DESCRIPTION
**Pull request by drktfl**
I am not sure if the `@types/...` packages are really missing or if the intention was to use a completely different package.

### CODE REVIEW

**Comment by nlunets** [comment]
Hmmm i would not push a new version of the mockserver for this :)

**Comment by drktfl** [comment]
> Hmmm i would not push a new version of the mockserver for this :)

true :)

**Comment by drktfl** [comment]
Btw.: Why did it still pass the CI/CD build but fail locally?

**Comment by nlunets** [comment]
no idea :)

**Review by nlunets — APPROVED** [review]

**Pull request merged**
