### PR TITLE
chore: reduce dependencies, support Node.js 20.x (LTS)

### PR DESCRIPTION
**Pull request by drktfl**
- Replacing axios and node-fetch with the `fetch()` implementation provided by Node.js (see https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch). 
- remove dependency to mkdirp
- Support the current Node.js LTS version (Node.js 20.x)

### CODE REVIEW

**Comment by nlunets** [comment]
node 16 is still in maintenance so i'm not sure about removing support for it there, especially since the codebase doesn't need node 18 :/

**Comment by drktfl** [comment]
it was such an easy approach to get rid of those dependencies 😉

**Comment by nlunets** [comment]
Well we can come back in september ;)

**Comment by drktfl** [comment]
but it is actually all internal use, in test code and in the generator in vocabularies-types. Not sure if those are meant to be run elsewhere

**Comment by nlunets** [comment]
not really, but you would now need to remove the pipeline runs for 14 and 16 which would be akin saying we drop support for them i guess :/

**Comment by nlunets** [comment]
[2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/) is in 5 days
I think we can rebase this one if you want @drktfl

**Comment by drktfl** [comment]
There is some progress on the types for the native fetch, we can probably wait a bit to remove the workarounds

**Review by nlunets — APPROVED** [review]
Nice !

**Pull request merged**
