### PR TITLE
feat: we now properly support root service document

### PR DESCRIPTION
**Pull request by nlunets**
Fix for #820 
We now properly create the service document for v2 and v4 services

### CODE REVIEW

**Comment by tobiasqueck** [comment]
@nlunets the standard xml response works but `?$format=json` seems to be ignored.

**Comment by nlunets** [comment]
I have tests specifically for this ;O
What request are you trying ?

**Comment by tobiasqueck** [comment]
> I have tests specifically for this ;O What request are you trying ?

http://localhost:8080/sap/opu/odata/IWFND/CATALOGSERVICE;v=2?$fomat=json

**Comment by nlunets** [comment]
[$fomat=json](http://localhost:8080/sap/opu/odata/IWFND/CATALOGSERVICE;v=2?$fomat=json)

**$fomat**

**Comment by tobiasqueck** [comment]
Stupid middleware! Why can it not auto-correct my typos like any other tool ;)

**Review by tobiasqueck — APPROVED** [review]
Tested locally and worked like a charm after spelling format correctly

**Pull request merged**
